### ISSUE TITLE
Is this runnable?

### ISSUE THREAD

**Issue by munkim** [mahmoudnafifi/modified-Poisson-image-editing#1]

**Comment by mahmoudnafifi** [comment]
Hi @munkim , I do not remember any issue in running the demo.m file, so can you please give some info about the error you got?

**Comment by mahmoudnafifi** [comment]
Okay, I am going to close this issue. Please let me know the problem if you are still interested by sending an email or create a new issue. Thanks!

**Comment by sofialeotag** [comment]
Hi @mahmoudnafifi , I am facing an error when running the demo.m in master branch.
The error occurs at line 52 of MPB.m, "A = A+speye(n)-I"; The error says that the sizes of the arrays are not compatible. I am running the 2nd set of the images. Could you please suggest how to fix this?

**Comment by mahmoudnafifi** [comment]
@sofialeotag please make sure that all images (source/target/masks) have the same dimensionalities.
